services:
  element-bot:
    image: ghcr.io/kappasigmamu/element-bot:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/data
    working_dir: /data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
