[alias]
chopsticks = "run --bin cargo-chopsticks --"
deploy = "run --bin deploy --"
dev = "run --bin cargo-dev --"
export = "run --bin export --"
seed = "run --bin seed --"
"society:bid" = "run --bin submit_bid --"
"society:unbid" = "run --bin unbid --"
